project_id = "family-cart"

[functions.add-household-user]
verify_jwt = true

[functions.complete-profile]
verify_jwt = true

[functions.register-user]
verify_jwt = false

[functions.finalize-registration]
verify_jwt = true

[functions.save-push-subscription]
verify_jwt = true

[functions.delete-push-subscription]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true
